<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Students Login Credentials</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            color: #222;
            padding: 20px;
        }

        .report-header {
            text-align: center;
            margin-bottom: 24px;
            border-bottom: 2px solid #1a1a2e;
            padding-bottom: 12px;
        }

        .report-header h1 {
            font-size: 18px;
            font-weight: bold;
            color: #1a1a2e;
            text-transform: uppercase;
            letter-spacing: 1px;
        }

        .report-header p {
            font-size: 10px;
            color: #555;
            margin-top: 4px;
        }

        .meta-info {
            font-size: 9.5px;
            color: #777;
            margin-bottom: 20px;
            text-align: right;
        }

        .class-section {
            margin-bottom: 24px;
            page-break-inside: avoid;
        }

        .class-title {
            background-color: #1a1a2e;
            color: #ffffff;
            padding: 6px 10px;
            font-size: 12px;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            margin-bottom: 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 4px;
        }

        thead tr {
            background-color: #e8eaf6;
        }

        thead th {
            padding: 6px 8px;
            text-align: left;
            font-size: 10px;
            font-weight: bold;
            color: #333;
            border: 1px solid #ccc;
        }

        tbody tr {
            border-bottom: 1px solid #e0e0e0;
        }

        tbody tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        tbody td {
            padding: 5px 8px;
            font-size: 10px;
            border: 1px solid #ddd;
            color: #333;
        }

        .s-no {
            width: 5%;
            text-align: center;
            color: #888;
        }

        .admission-col {
            width: 15%;
            font-weight: bold;
            color: #1a1a2e;
        }

        .name-col {
            width: 40%;
        }

        .class-col {
            width: 20%;
        }

        .password-col {
            width: 20%;
            font-family: monospace;
            font-size: 10px;
            color: #c0392b;
            font-weight: bold;
        }

        .student-count {
            font-size: 9px;
            color: #888;
            text-align: right;
            padding: 2px 4px;
            margin-bottom: 6px;
        }

        .footer {
            margin-top: 30px;
            border-top: 1px solid #ccc;
            padding-top: 8px;
            font-size: 9px;
            color: #999;
            text-align: center;
        }

        .warning-box {
            background-color: #fff8e1;
            border-left: 4px solid #f39c12;
            padding: 8px 12px;
            margin-bottom: 20px;
            font-size: 10px;
            color: #7d5a00;
        }

        .total-summary {
            text-align: right;
            font-size: 10px;
            font-weight: bold;
            color: #555;
            margin-top: 16px;
        }
    </style>
</head>
<body>

    <div class="report-header">
        <h1>Student Login Credentials</h1>
        <p>Admission Numbers, Names, Classes &amp; Default Passwords</p>
    </div>

    <div class="meta-info">
        Generated on: {{ $generatedAt }} &nbsp;|&nbsp; Generated by: {{ $generatedBy }}
    </div>

    <div class="warning-box">
        &#9888; <strong>Confidential:</strong> This document contains login credentials.
        Please distribute securely and advise students to change their passwords after first login.
        Default password for all students is <strong>12345</strong>.
    </div>

    @php $grandTotal = 0; @endphp

    @foreach($groupedByClass as $className => $students)
        @php $grandTotal += $students->count(); @endphp

        <div class="class-section">
            <div class="class-title">{{ $className }}</div>
            <div class="student-count">{{ $students->count() }} student(s)</div>

            <table>
                <thead>
                    <tr>
                        <th class="s-no">#</th>
                        <th class="admission-col">Admission No</th>
                        <th class="name-col">Student Name</th>
                        <th class="class-col">Class</th>
                        <th class="password-col">Default Password</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($students as $index => $student)
                        <tr>
                            <td class="s-no">{{ $index + 1 }}</td>
                            <td class="admission-col">{{ $student->admission_no ?? 'N/A' }}</td>
                            <td class="name-col">{{ $student->name }}</td>
                            <td class="class-col">{{ $student->class->name ?? 'N/A' }}</td>
                            <td class="password-col">12345</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    @endforeach

    <div class="total-summary">
        Total Students: {{ $grandTotal }}
    </div>

    <div class="footer">
        This document is auto-generated and intended for administrative use only. &nbsp;|&nbsp;
        {{ config('app.name') }} &mdash; {{ now()->format('Y') }}
    </div>

</body>
</html>